import Australia1 from '../../Assets/Australia1.jpg';
import Insurance from '../../Assets/Insurance.png';
export const hotelData=[
    {
      Hotelid:'Hotel1',
      HotelOverview: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      HotelheaderImages: [Australia1, Australia1, Australia1, Australia1,Australia1,Australia1,Australia1,Australia1,],
      Hotelimage: Insurance,
      WTRecommended: true,  // Add this field to determine if the insurance is excluded
      Hotelrating: 3,
      Hotelamount:'Refundable', 
      HotelDate:"12/04/2024", 
      Hotelarea:"Area 538 sqft", 
      Hoteltype:'5 Star',
      Hotelcheckintime:'14:00',
      Hotelcheckouttime:'14:00', 
      Hotelname:'Pucket Yotel1',
      Hotelaccomodates:'Accommodates 3 Adults', 
      Hotelinclusions:["Wifi","Room with Breakfast",'Air Conditioner'],
      Hotelexclusions:["Elevator","Bathtub"],
      HotelNearbyAttractions:[
        "Silom Complex Shopping Mall - 0.7 km / 0.5 mi",
        "Lumphini Park - 0.8 km / 0.5 mi",
        'Thaniya Plaza - 1.1 km / 0.7 mi',
        "Chulalongkorn Hospital - 1.2 km / 0.7 mi",
        "Chulalongkorn University - 1.4 km / 0.9 mi",
        'King Power MahaNakhon - 1.4 km / 0.9 mi',
        "Wat Hua Lamphong - 1.7 km / 1.1 mi",
        "Embassy of the United States - 1.9 km / 1.2 mi",
        'Samyan Mitrtown - 1.9 km / 1.2 mi',
        "Stock Exchange of Thailand - 2.7 km / 1.6 mi",
        "Siam Square - 2.7 km / 1.7 mi",
        'Erawan Shrine - 2.8 km / 1.7 mi',
      ],
      HotelAmenties:[
        "Elevator facility",
        "Concierge Service",
        'Laundry facility',
        "Common storage facility",
        "Pool accessories",
        'Locker Facility',
        "Gym/Fitness Centre",
        "Parking Facility",
        'Shuttle Service',
        "Spa facility",
        "Childcare Supervision",
      ],
      HotelInfo:'Hotels may charge a caution deposit on your credit card. It will be refunded within 10-15 days if there is no property damage.',
      Hoteladdress:'21/100 South Sathon Road,Bangkok,Bangkok,10120,TH ',
      HotelCategory:"Villa"
    },
    {
      Hotelid:'Hotel2',
      HotelOverview: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      HotelheaderImages: [Insurance, Insurance, Insurance, Insurance, Insurance, Insurance, Insurance, Insurance,],
      Hotelimage: Insurance,
      WTRecommended: false,  // Add this field to determine if the insurance is excluded
      Hotelrating: 4.5,
      Hotelamount:'Refundable', 
      HotelDate:"12/04/2024", 
      Hotelarea:"Area 538 sqft", 
      Hoteltype:'5 Star', 
      Hotelname:'Pucket Yotel',
      Hotelaccomodates:'Accommodates 3 Adults', 
      Hotelinclusions:["Wifi","Room with Breakfast",'Air Conditioner'],
      Hotelexclusions:["Elevator","Bathtub"], 
      HotelInfo:'Hotels may charge a caution deposit on your credit card. It will be refunded within 10-15 days if there is no property damage.',
      Hoteladdress:'21/100 South Sathon Road,Bangkok,Bangkok,10120,TH ',
    },
    {
        Hotelid:'Hotel3',
        HotelOverview: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        HotelheaderImages: [Australia1, Australia1, Australia1, Australia1,Australia1,Australia1,Australia1,Australia1,],
        Hotelimage: Insurance,
        WTRecommended: true,  // Add this field to determine if the insurance is excluded
        Hotelrating: 4.5,
        Hotelamount:'Refundable', 
        HotelDate:"12/04/2024", 
        Hotelarea:"Area 538 sqft", 
        Hoteltype:'5 Star',
        Hotelcheckintime:'14:00',
        Hotelcheckouttime:'14:00', 
        Hotelname:'Pucket Yotel3',
        Hotelaccomodates:'Accommodates 3 Adults', 
        Hotelinclusions:["Wifi","Room with Breakfast",'Air Conditioner'],
        Hotelexclusions:["Elevator","Bathtub"],
        HotelNearbyAttractions:[
          "Silom Complex Shopping Mall - 0.7 km / 0.5 mi",
          "Lumphini Park - 0.8 km / 0.5 mi",
          'Thaniya Plaza - 1.1 km / 0.7 mi',
          "Chulalongkorn Hospital - 1.2 km / 0.7 mi",
          "Chulalongkorn University - 1.4 km / 0.9 mi",
          'King Power MahaNakhon - 1.4 km / 0.9 mi',
          "Wat Hua Lamphong - 1.7 km / 1.1 mi",
          "Embassy of the United States - 1.9 km / 1.2 mi",
          'Samyan Mitrtown - 1.9 km / 1.2 mi',
          "Stock Exchange of Thailand - 2.7 km / 1.6 mi",
          "Siam Square - 2.7 km / 1.7 mi",
          'Erawan Shrine - 2.8 km / 1.7 mi',
        ],
        HotelAmenties:[
          "Elevator facility",
          "Concierge Service",
          'Laundry facility',
          "Common storage facility",
          "Pool accessories",
          'Locker Facility',
          "Gym/Fitness Centre",
          "Parking Facility",
          'Shuttle Service',
          "Spa facility",
          "Childcare Supervision",
        ],
        HotelInfo:'Hotels may charge a caution deposit on your credit card. It will be refunded within 10-15 days if there is no property damage.',
        Hoteladdress:'21/100 South Sathon Road,Bangkok,Bangkok,10120,TH ',
    },
    {
        Hotelid:'Hotel4',
        HotelOverview: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        HotelheaderImages: [Insurance, Insurance, Insurance, Insurance, Insurance, Insurance, Insurance, Insurance,],
        Hotelimage: Insurance,
        WTRecommended: false,  // Add this field to determine if the insurance is excluded
        Hotelrating: 4.5,
        Hotelamount:'Refundable', 
        HotelDate:"12/04/2024", 
        Hotelarea:"Area 538 sqft", 
        Hoteltype:'5 Star', 
        Hotelname:'Pucket Yotel4',
        Hotelaccomodates:'Accommodates 3 Adults', 
        Hotelinclusions:["Wifi","Room with Breakfast",'Air Conditioner'],
        Hotelexclusions:["Elevator","Bathtub"], 
        HotelInfo:'Hotels may charge a caution deposit on your credit card. It will be refunded within 10-15 days if there is no property damage.',
        Hoteladdress:'21/100 South Sathon Road,Bangkok,Bangkok,10120,TH ',
    },
  ];