import React, {useState} from 'react';
import { useMediaQuery } from "react-responsive";
import './Filterpackagelisting.css';
import Pattaya from '../../Assets/Pattaya.jpg';
import Thailand from '../../Assets/Thailand.jpg';
import Abudhabi from '../../Assets/Abudhabi.jpg';
import Australia1 from '../../Assets/Australia1.jpg';
import Filter from '../Listingfilter/Filter';
import { MdFlight } from "react-icons/md";
import { TbTrekking } from "react-icons/tb";
import { FaCarSide } from "react-icons/fa6";
import { RiHotelFill } from "react-icons/ri";
import Insurance from '../../Assets/Insurance.png';
import Flight1 from '../../Assets/Flight1.png';
import Flight2 from '../../Assets/Flight1.png';
import PackageListing from '../Packagelisting/Packagelisting';

export default function Filterpackagelisting(){
  const isMobile = useMediaQuery({ query: "(max-width: 820px)" });
    const [filters, setFilters] = useState({
        budget: [],
        noOfDays: [],
        rating: [],
      });
      
      const [packages, setPackages] = useState([
        {
          id: 1,
          TravellingDate:"Oct 05 2024",
          TravellingFrom:"BLR",
          NoofAdults:"2 Adults",
          NoofChildren:"4 Children",
          Rooms:"1 Room",
          Images:[Thailand, Abudhabi, Australia1, Thailand, Thailand, Thailand, Thailand, Thailand, Thailand],
          Flighticon: <MdFlight className='flighticon' />,
          Activityicon: <TbTrekking className='Activityicon' />,
          Transfericon: <FaCarSide className='Transfericon' />,
          Hotelicon: <RiHotelFill className='Hotelicon' />,
          title: "8N/4 Days Dazzling Phuket Pattaya Package",
          rating: 4.5,
          originalprice: 30000,
          offerprice: 26034,
          offerpercentage: 8,
          days: 4,
          EMI:"3472",
          loyality:"611",
          info:"dkhashgdvgsdvgasv",
          Inclusions:["wifi","Room with breakfast", "Air Conditioner"],
          Exclusions:["Elevator","Bathtub"],
          amenties:["5 Star","9 Activities", "Shared Transfer" , "24/7 Concierge"],
          image: Pattaya, // Use the actual image link
          information:'Filler text is text that shares some characteristics of a real written text, but is random or otherwise generated. It may be used to display a sample of fonts, generate text for testing, or to spoof an e-mail spam filterFiller text is text that shares some characteristics of a real written text, but is random or otherwise generated. It may be used to display a sample of fonts, generate text for testing, or to spoof an e-mail spam filterFiller text is text that shares some characteristics of a real written text, but is random or otherwise generated. It may be used to display a sample of fonts, generate text for testing, or to spoof an e-mail spam filter.Filler text is text that shares some characteristics of a real written text, but is random or otherwise generated. It may be used to display a sample of fonts, generate text for testing, or to spoof an e-mail spam filterFiller text is text that shares some characteristics of a real written text, but is random or otherwise generated. It may be used to display a sample of fonts, generate text for testing, or to spoof an e-mail spam filterFiller text is text that shares some characteristics of a real written text, but is random or otherwise generated. It may be used to display a sample of fonts, generate text for testing, or to spoof an e-mail spam filter.',
          Travelexpert:{
            Travelexpertid:1,
            Travelexpertname:"Manimala",
            Tripsplannedsofar:10,
            Travelexpertimage:Insurance,
          },
          Sendemail:{
            Tittle:"ImportantHolidayAlerts",
            Subtittle1:"ThingsToPlanForBeforeDeparture",
            listing1:[
              "Your Bengaluru to Kochi flight has a lengthy layover of 10h 45m at Kochi airport, which may be tiring and you might require a transit visa to step out of the airport.",
          "Your Maldives to Kochi flight has a lengthy layover of 17h 10m at Kochi airport, which may be tiring and you might require a transit visa to step out of the airport.",
          "The Cocogiri Island Resort Maldives in Maldives does not have an elevator."
            ],
            Subtittle2:"Things to know before departure",
            listing2:[
              "Your Bengaluru to Kochi flight has a lengthy layover of 10h 45m at Kochi airport, which may be tiring and you might require a transit visa to step out of the airport.",
          "Your Maldives to Kochi flight has a lengthy layover of 17h 10m at Kochi airport, which may be tiring and you might require a transit visa to step out of the airport.",
          "The Cocogiri Island Resort Maldives in Maldives does not have an elevator."
            ],
          },
          Days:[
            { 
              tittle:'1 Get ready to enjoy a trip most romantic in Bali',
              Description:'Arrive at the Ngurah Rai International Airport in Bali, where you will be met by a representative of your chosen travel agent. You will be transferred to your hotel in Kuta, where you check in and can relax for a while. You have the rest of the day at leisure, so you can go ahead and explore the area around your hotel. Spend some time at the beach, or take a look at the local markets as per such Bali honeymoon packages.',
              DayImages:[Insurance, Insurance, Insurance, Insurance, Insurance],
              Morning:true,
              MorningAddActivity:false,
              MorningFlight:true,
              MorningActivity:true,
              MorningHotel:true,
              MorningTransfer:true,
              MorningHoteldescription:"Morning hotel description",
              MorningTransferdescription:"Morning transfer description",
              MorningFlightdescription:"Morning flight description",
              MorningActivitydescription:"Morning activity description",
              Afternoon:true,
              AfternoonAddActivity:false,
              AfternoonFlight:false,
              AfternoonActivity:true,
              AfternoonHotel:true,
              AfternoonTransfer:true,
              AfternoonHoteldescription:"Afternoon hotel description",
              AfternoonTransferdescription:"Afternoon transfer description",
              AfternoonFlightdescription:"Afternoon flight description",
              AfternoonActivitydescription:"Afternoon activity description",
              Evening:true,
              EveningAddActivity:false,
              EveningFlight:false,
              EveningActivity:false,
              EveningHotel:true,
              EveningTransfer:true,
              EveningHoteldescription:"Evening hotel description",
              EveningTransferdescription:"Evening transfer description",
              EveningFlightdescription:"Evening flight description",
              EveningActivitydescription:"Evening activity description",
              MorningAfternoon:false,
              MorningAfternoonAddActivity: false,
              MorningAfternoonFlight:false,
              MorningAfternoonActivity:false,
              MorningAfternoonHotel:false,
              MorningAfternoonTransfer:false,
              MorningAfternoonHoteldescription:"Morning Afternoon hotel description",
              MorningAfternoonTransferdescription:"Morning Afternoon transfer description",
              MorningAfternoonFlightdescription:"Morning Afternoon flight description",
              MorningAfternoonActivitydescription:"Morning Afternoon activity description",
              AfternoonEvening:false,
              AfternoonEveningAddActivity: false,
              AfternoonEveningFlight:false,
              AfternoonEveningActivity:false,
              AfternoonEveningHotel:false,
              AfternoonEveningTransfer:false,
              AfternoonEveningHoteldescription:"Afternoon Evening hotel description",
              AfternoonEveningTransferdescription:"Afternoon Evening transfer description",
              AfternoonEveningFlightdescription:"Afternoon Evening flight description",
              AfternoonEveningActivitydescription:"Afternoon Evening activity description",
              Fullday:false,
              FulldayAddActivity: false,
              FulldayHotel:false,
              FulldayActivity:false,
              FulldayFlight:false,
              FulldayTransfer:false,
              FulldayHoteldescription:"Morning hotel description",
              FulldayTransferdescription:"Morning transfer description",
              FulldayFlightdescription:"Morning flight description",
              FulldayActivitydescription:"Morning activity description",
            },
            {
              tittle:'2 Get ready to enjoy a trip most romantic in Bali',
              Description:'Arrive at the Ngurah Rai International Airport in Bali, where you will be met by a representative of your chosen travel agent. You will be transferred to your hotel in Kuta, where you check in and can relax for a while. You have the rest of the day at leisure, so you can go ahead and explore the area around your hotel. Spend some time at the beach, or take a look at the local markets as per such Bali honeymoon packages.',
              DayImages:[Insurance, Insurance, Insurance, Insurance, Insurance],
              Morning:true,
              MorningAddActivity:true,
              MorningFlight:false,
              MorningActivity:false,
              MorningHotel:false,
              MorningTransfer:false,
              MorningHoteldescription:"Morning hotel description",
              MorningTransferdescription:"Morning transfer description",
              MorningFlightdescription:"Morning flight description",
              MorningActivitydescription:"Morning activity description",
              Afternoon:true,
              AfternoonAddActivity:false,
              AfternoonFlight:false,
              AfternoonActivity:false,
              AfternoonHotel:false,
              AfternoonTransfer:true,
              AfternoonHoteldescription:"Afternoon hotel description",
              AfternoonTransferdescription:"Afternoon transfer description",
              AfternoonFlightdescription:"Afternoon flight description",
              AfternoonActivitydescription:"Afternoon activity description",
              Evening:true,
              EveningAddActivity:false,
              EveningFlight:true,
              EveningActivity:true,
              EveningHotel:true,
              EveningTransfer:true,
              EveningHoteldescription:"Evening hotel description",
              EveningTransferdescription:"Evening transfer description",
              EveningFlightdescription:"Evening flight description",
              EveningActivitydescription:"Evening activity description",
              MorningAfternoon:false,
              MorningAfternoonAddActivity: false,
              MorningAfternoonFlight:false,
              MorningAfternoonActivity:false,
              MorningAfternoonHotel:false,
              MorningAfternoonTransfer:false,
              MorningAfternoonHoteldescription:"Morning Afternoon hotel description",
              MorningAfternoonTransferdescription:"Morning Afternoon transfer description",
              MorningAfternoonFlightdescription:"Morning Afternoon flight description",
              MorningAfternoonActivitydescription:"Morning Afternoon activity description",
              AfternoonEvening:false,
              AfternoonEveningAddActivity: false,
              AfternoonEveningFlight:false,
              AfternoonEveningActivity:false,
              AfternoonEveningHotel:false,
              AfternoonEveningTransfer:false,
              AfternoonEveningHoteldescription:"Afternoon Evening hotel description",
              AfternoonEveningTransferdescription:"Afternoon Evening transfer description",
              AfternoonEveningFlightdescription:"Afternoon Evening flight description",
              AfternoonEveningActivitydescription:"Afternoon Evening activity description",
              Fullday:false,
              FulldayAddActivity: false,
              FulldayHotel:false,
              FulldayActivity:false,
              FulldayFlight:false,
              FulldayTransfer:false,
              FulldayHoteldescription:"Morning hotel description",
              FulldayTransferdescription:"Morning transfer description",
              FulldayFlightdescription:"Morning flight description",
              FulldayActivitydescription:"Morning activity description",
            },
            { 
              tittle:'3 Get ready to enjoy a trip most romantic in Bali',
              Description:'Arrive at the Ngurah Rai International Airport in Bali, where you will be met by a representative of your chosen travel agent. You will be transferred to your hotel in Kuta, where you check in and can relax for a while. You have the rest of the day at leisure, so you can go ahead and explore the area around your hotel. Spend some time at the beach, or take a look at the local markets as per such Bali honeymoon packages.',
              DayImages:[Insurance, Insurance, Insurance, Insurance, Insurance],
              Morning:false,
              MorningAddActivity:false,
              MorningFlight:true,
              MorningActivity:true,
              MorningHotel:true,
              MorningTransfer:true,
              MorningHoteldescription:"Morning hotel description",
              MorningTransferdescription:"Morning transfer description",
              MorningFlightdescription:"Morning flight description",
              MorningActivitydescription:"Morning activity description",
              Afternoon:false,
              AfternoonAddActivity:false,
              AfternoonFlight:true,
              AfternoonActivity:true,
              AfternoonHotel:true,
              AfternoonTransfer:true,
              AfternoonHoteldescription:"Afternoon hotel description",
              AfternoonTransferdescription:"Afternoon transfer description",
              AfternoonFlightdescription:"Afternoon flight description",
              AfternoonActivitydescription:"Afternoon activity description",
              Evening:true,
              EveningAddActivity:false,
              EveningFlight:true,
              EveningActivity:true,
              EveningHotel:true,
              EveningTransfer:true,
              EveningHoteldescription:"Evening hotel description",
              EveningTransferdescription:"Evening transfer description",
              EveningFlightdescription:"Evening flight description",
              EveningActivitydescription:"Evening activity description",
              MorningAfternoon:true,
              MorningAfternoonAddActivity: true,
              MorningAfternoonFlight:false,
              MorningAfternoonActivity:false,
              MorningAfternoonHotel:false,
              MorningAfternoonTransfer:false,
              MorningAfternoonHoteldescription:"Morning Afternoon hotel description",
              MorningAfternoonTransferdescription:"Morning Afternoon transfer description",
              MorningAfternoonFlightdescription:"Morning Afternoon flight description",
              MorningAfternoonActivitydescription:"Morning Afternoon activity description",
              AfternoonEvening:false,
              AfternoonEveningAddActivity: false,
              AfternoonEveningFlight:false,
              AfternoonEveningActivity:false,
              AfternoonEveningHotel:false,
              AfternoonEveningTransfer:false,
              AfternoonEveningHoteldescription:"Afternoon Evening hotel description",
              AfternoonEveningTransferdescription:"Afternoon Evening transfer description",
              AfternoonEveningFlightdescription:"Afternoon Evening flight description",
              AfternoonEveningActivitydescription:"Afternoon Evening activity description",
              Fullday:false,
              FulldayAddActivity: false,
              FulldayHotel:false,
              FulldayActivity:false,
              FulldayFlight:false,
              FulldayTransfer:false,
              FulldayHoteldescription:"Morning hotel description",
              FulldayTransferdescription:"Morning transfer description",
              FulldayFlightdescription:"Morning flight description",
              FulldayActivitydescription:"Morning activity description",
            },
            {
              tittle:'4 Get ready to enjoy a trip most romantic in Bali',
              Description:'Arrive at the Ngurah Rai International Airport in Bali, where you will be met by a representative of your chosen travel agent. You will be transferred to your hotel in Kuta, where you check in and can relax for a while. You have the rest of the day at leisure, so you can go ahead and explore the area around your hotel. Spend some time at the beach, or take a look at the local markets as per such Bali honeymoon packages.',
              DayImages:[Insurance, Insurance, Insurance, Insurance, Insurance],
              Morning:true,
              MorningAddActivity:false,
              MorningFlight:true,
              MorningActivity:true,
              MorningHotel:true,
              MorningTransfer:true,
              MorningHoteldescription:"Morning hotel description",
              MorningTransferdescription:"Morning transfer description",
              MorningFlightdescription:"Morning flight description",
              MorningActivitydescription:"Morning activity description",
              Afternoon:false,
              AfternoonAddActivity:false,
              AfternoonFlight:true,
              AfternoonActivity:true,
              AfternoonHotel:true,
              AfternoonTransfer:true,
              AfternoonHoteldescription:"Afternoon hotel description",
              AfternoonTransferdescription:"Afternoon transfer description",
              AfternoonFlightdescription:"Afternoon flight description",
              AfternoonActivitydescription:"Afternoon activity description",
              Evening:false,
              EveningAddActivity:false,
              EveningFlight:true,
              EveningActivity:true,
              EveningHotel:true,
              EveningTransfer:true,
              EveningHoteldescription:"Evening hotel description",
              EveningTransferdescription:"Evening transfer description",
              EveningFlightdescription:"Evening flight description",
              EveningActivitydescription:"Evening activity description",
              MorningAfternoon:false,
              MorningAfternoonAddActivity: false,
              MorningAfternoonFlight:false,
              MorningAfternoonActivity:false,
              MorningAfternoonHotel:false,
              MorningAfternoonTransfer:false,
              MorningAfternoonHoteldescription:"Morning Afternoon hotel description",
              MorningAfternoonTransferdescription:"Morning Afternoon transfer description",
              MorningAfternoonFlightdescription:"Morning Afternoon flight description",
              MorningAfternoonActivitydescription:"Morning Afternoon activity description",
              AfternoonEvening:true,
              AfternoonEveningAddActivity: true,
              AfternoonEveningFlight:false,
              AfternoonEveningActivity:false,
              AfternoonEveningHotel:false,
              AfternoonEveningTransfer:false,
              AfternoonEveningHoteldescription:"Afternoon Evening hotel description",
              AfternoonEveningTransferdescription:"Afternoon Evening transfer description",
              AfternoonEveningFlightdescription:"Afternoon Evening flight description",
              AfternoonEveningActivitydescription:"Afternoon Evening activity description",
              Fullday:false,
              FulldayAddActivity: false,
              FulldayHotel:false,
              FulldayActivity:false,
              FulldayFlight:false,
              FulldayTransfer:false,
              FulldayHoteldescription:"Morning hotel description",
              FulldayTransferdescription:"Morning transfer description",
              FulldayFlightdescription:"Morning flight description",
              FulldayActivitydescription:"Morning activity description",
            },
            {
              tittle:'5 Get ready to enjoy a trip most romantic in Bali',
              Description:'Arrive at the Ngurah Rai International Airport in Bali, where you will be met by a representative of your chosen travel agent. You will be transferred to your hotel in Kuta, where you check in and can relax for a while. You have the rest of the day at leisure, so you can go ahead and explore the area around your hotel. Spend some time at the beach, or take a look at the local markets as per such Bali honeymoon packages.',
              DayImages:[Insurance, Insurance, Insurance, Insurance, Insurance],
              Morning:false,
              MorningAddActivity:false,
              MorningFlight:false,
              MorningActivity:false,
              MorningHotel:false,
              MorningTransfer:false,
              MorningHoteldescription:"Morning hotel description",
              MorningTransferdescription:"Morning transfer description",
              MorningFlightdescription:"Morning flight description",
              MorningActivitydescription:"Morning activity description",
              Afternoon:false,
              AfternoonAddActivity:false,
              AfternoonFlight:true,
              AfternoonActivity:true,
              AfternoonHotel:true,
              AfternoonTransfer:true,
              AfternoonHoteldescription:"Afternoon hotel description",
              AfternoonTransferdescription:"Afternoon transfer description",
              AfternoonFlightdescription:"Afternoon flight description",
              AfternoonActivitydescription:"Afternoon activity description",
              Evening:false,
              EveningAddActivity:false,
              EveningFlight:true,
              EveningActivity:true,
              EveningHotel:true,
              EveningTransfer:true,
              EveningHoteldescription:"Evening hotel description",
              EveningTransferdescription:"Evening transfer description",
              EveningFlightdescription:"Evening flight description",
              EveningActivitydescription:"Evening activity description",
              MorningAfternoon:false,
              MorningAfternoonAddActivity: false,
              MorningAfternoonFlight:false,
              MorningAfternoonActivity:false,
              MorningAfternoonHotel:false,
              MorningAfternoonTransfer:false,
              MorningAfternoonHoteldescription:"Morning Afternoon hotel description",
              MorningAfternoonTransferdescription:"Morning Afternoon transfer description",
              MorningAfternoonFlightdescription:"Morning Afternoon flight description",
              MorningAfternoonActivitydescription:"Morning Afternoon activity description",
              AfternoonEvening:false,
              AfternoonEveningAddActivity: false,
              AfternoonEveningFlight:false,
              AfternoonEveningActivity:false,
              AfternoonEveningHotel:false,
              AfternoonEveningTransfer:false,
              AfternoonEveningHoteldescription:"Afternoon Evening hotel description",
              AfternoonEveningTransferdescription:"Afternoon Evening transfer description",
              AfternoonEveningFlightdescription:"Afternoon Evening flight description",
              AfternoonEveningActivitydescription:"Afternoon Evening activity description",
              Fullday:true,
              FulldayAddActivity: true,
              FulldayHotel:false,
              FulldayActivity:false,
              FulldayFlight:false,
              FulldayTransfer:false,
              FulldayHoteldescription:"Morning hotel description",
              FulldayTransferdescription:"Morning transfer description",
              FulldayFlightdescription:"Morning flight description",
              FulldayActivitydescription:"Morning activity description",
            },
            {
              tittle:'6 Get ready to enjoy a trip most romantic in Bali',
              Description:'Arrive at the Ngurah Rai International Airport in Bali, where you will be met by a representative of your chosen travel agent. You will be transferred to your hotel in Kuta, where you check in and can relax for a while. You have the rest of the day at leisure, so you can go ahead and explore the area around your hotel. Spend some time at the beach, or take a look at the local markets as per such Bali honeymoon packages.',
              DayImages:[Insurance, Insurance, Insurance, Insurance, Insurance],
              Morning:false,
              MorningAddActivity:false,
              MorningFlight:false,
              MorningActivity:false,
              MorningHotel:false,
              MorningTransfer:false,
              MorningHoteldescription:"Morning hotel description",
              MorningTransferdescription:"Morning transfer description",
              MorningFlightdescription:"Morning flight description",
              MorningActivitydescription:"Morning activity description",
              Afternoon:false,
              AfternoonAddActivity:false,
              AfternoonFlight:true,
              AfternoonActivity:true,
              AfternoonHotel:true,
              AfternoonTransfer:true,
              AfternoonHoteldescription:"Afternoon hotel description",
              AfternoonTransferdescription:"Afternoon transfer description",
              AfternoonFlightdescription:"Afternoon flight description",
              AfternoonActivitydescription:"Afternoon activity description",
              Evening:false,
              EveningAddActivity:false,
              EveningFlight:true,
              EveningActivity:true,
              EveningHotel:true,
              EveningTransfer:true,
              EveningHoteldescription:"Evening hotel description",
              EveningTransferdescription:"Evening transfer description",
              EveningFlightdescription:"Evening flight description",
              EveningActivitydescription:"Evening activity description",
              MorningAfternoon:false,
              MorningAfternoonAddActivity: false,
              MorningAfternoonFlight:false,
              MorningAfternoonActivity:false,
              MorningAfternoonHotel:false,
              MorningAfternoonTransfer:false,
              MorningAfternoonHoteldescription:"Morning Afternoon hotel description",
              MorningAfternoonTransferdescription:"Morning Afternoon transfer description",
              MorningAfternoonFlightdescription:"Morning Afternoon flight description",
              MorningAfternoonActivitydescription:"Morning Afternoon activity description",
              AfternoonEvening:false,
              AfternoonEveningAddActivity: false,
              AfternoonEveningFlight:false,
              AfternoonEveningActivity:false,
              AfternoonEveningHotel:false,
              AfternoonEveningTransfer:false,
              AfternoonEveningHoteldescription:"Afternoon Evening hotel description",
              AfternoonEveningTransferdescription:"Afternoon Evening transfer description",
              AfternoonEveningFlightdescription:"Afternoon Evening flight description",
              AfternoonEveningActivitydescription:"Afternoon Evening activity description",
              Fullday:true,
              FulldayAddActivity: false,
              FulldayHotel:true,
              FulldayActivity:true,
              FulldayFlight:true,
              FulldayTransfer:true,
              FulldayHoteldescription:"Morning hotel description",
              FulldayTransferdescription:"Morning transfer description",
              FulldayFlightdescription:"Morning flight description",
              FulldayActivitydescription:"Morning activity description",
            },
            {
              tittle:'7 Get ready to enjoy a trip most romantic in Bali',
              Description:'Arrive at the Ngurah Rai International Airport in Bali, where you will be met by a representative of your chosen travel agent. You will be transferred to your hotel in Kuta, where you check in and can relax for a while. You have the rest of the day at leisure, so you can go ahead and explore the area around your hotel. Spend some time at the beach, or take a look at the local markets as per such Bali honeymoon packages.',
              DayImages:[Insurance, Insurance, Insurance, Insurance, Insurance],
              Morning:true,
              MorningAddActivity:false,
              MorningFlight:true,
              MorningActivity:true,
              MorningHotel:true,
              MorningTransfer:true,
              MorningHoteldescription:"Morning hotel description",
              MorningTransferdescription:"Morning transfer description",
              MorningFlightdescription:"Morning flight description",
              MorningActivitydescription:"Morning activity description",
              Afternoon:false,
              AfternoonAddActivity:false,
              AfternoonFlight:true,
              AfternoonActivity:true,
              AfternoonHotel:true,
              AfternoonTransfer:true,
              AfternoonHoteldescription:"Afternoon hotel description",
              AfternoonTransferdescription:"Afternoon transfer description",
              AfternoonFlightdescription:"Afternoon flight description",
              AfternoonActivitydescription:"Afternoon activity description",
              Evening:false,
              EveningAddActivity:false,
              EveningFlight:true,
              EveningActivity:true,
              EveningHotel:true,
              EveningTransfer:true,
              EveningHoteldescription:"Evening hotel description",
              EveningTransferdescription:"Evening transfer description",
              EveningFlightdescription:"Evening flight description",
              EveningActivitydescription:"Evening activity description",
              MorningAfternoon:false,
              MorningAfternoonAddActivity: false,
              MorningAfternoonFlight:false,
              MorningAfternoonActivity:false,
              MorningAfternoonHotel:false,
              MorningAfternoonTransfer:false,
              MorningAfternoonHoteldescription:"Morning Afternoon hotel description",
              MorningAfternoonTransferdescription:"Morning Afternoon transfer description",
              MorningAfternoonFlightdescription:"Morning Afternoon flight description",
              MorningAfternoonActivitydescription:"Morning Afternoon activity description",
              AfternoonEvening:true,
              AfternoonEveningAddActivity: false,
              AfternoonEveningFlight:true,
              AfternoonEveningActivity:true,
              AfternoonEveningHotel:true,
              AfternoonEveningTransfer:true,
              AfternoonEveningHoteldescription:"Afternoon Evening hotel description",
              AfternoonEveningTransferdescription:"Afternoon Evening transfer description",
              AfternoonEveningFlightdescription:"Afternoon Evening flight description",
              AfternoonEveningActivitydescription:"Afternoon Evening activity description",
              Fullday:false,
              FulldayAddActivity: false,
              FulldayHotel:false,
              FulldayActivity:false,
              FulldayFlight:false,
              FulldayTransfer:false,
              FulldayHoteldescription:"Morning hotel description",
              FulldayTransferdescription:"Morning transfer description",
              FulldayFlightdescription:"Morning flight description",
              FulldayActivitydescription:"Morning activity description",
            },
            { 
              tittle:'8 Get ready to enjoy a trip most romantic in Bali',
              Description:'Arrive at the Ngurah Rai International Airport in Bali, where you will be met by a representative of your chosen travel agent. You will be transferred to your hotel in Kuta, where you check in and can relax for a while. You have the rest of the day at leisure, so you can go ahead and explore the area around your hotel. Spend some time at the beach, or take a look at the local markets as per such Bali honeymoon packages.',
              DayImages:[Insurance, Insurance, Insurance, Insurance, Insurance],
              Morning:false,
              MorningAddActivity:false,
              MorningFlight:true,
              MorningActivity:true,
              MorningHotel:true,
              MorningTransfer:true,
              MorningHoteldescription:"Morning hotel description",
              MorningTransferdescription:"Morning transfer description",
              MorningFlightdescription:"Morning flight description",
              MorningActivitydescription:"Morning activity description",
              Afternoon:false,
              AfternoonAddActivity:false,
              AfternoonFlight:true,
              AfternoonActivity:true,
              AfternoonHotel:true,
              AfternoonTransfer:true,
              AfternoonHoteldescription:"Afternoon hotel description",
              AfternoonTransferdescription:"Afternoon transfer description",
              AfternoonFlightdescription:"Afternoon flight description",
              AfternoonActivitydescription:"Afternoon activity description",
              Evening:true,
              EveningAddActivity:false,
              EveningFlight:true,
              EveningActivity:true,
              EveningHotel:true,
              EveningTransfer:true,
              EveningHoteldescription:"Evening hotel description",
              EveningTransferdescription:"Evening transfer description",
              EveningFlightdescription:"Evening flight description",
              EveningActivitydescription:"Evening activity description",
              MorningAfternoon:true,
              MorningAfternoonAddActivity: false,
              MorningAfternoonFlight:true,
              MorningAfternoonActivity:true,
              MorningAfternoonHotel:true,
              MorningAfternoonTransfer:true,
              MorningAfternoonHoteldescription:"Morning Afternoon hotel description",
              MorningAfternoonTransferdescription:"Morning Afternoon transfer description",
              MorningAfternoonFlightdescription:"Morning Afternoon flight description",
              MorningAfternoonActivitydescription:"Morning Afternoon activity description",
              AfternoonEvening:false,
              AfternoonEveningAddActivity: false,
              AfternoonEveningFlight:false,
              AfternoonEveningActivity:false,
              AfternoonEveningHotel:false,
              AfternoonEveningTransfer:false,
              AfternoonEveningHoteldescription:"Afternoon Evening hotel description",
              AfternoonEveningTransferdescription:"Afternoon Evening transfer description",
              AfternoonEveningFlightdescription:"Afternoon Evening flight description",
              AfternoonEveningActivitydescription:"Afternoon Evening activity description",
              Fullday:false,
              FulldayAddActivity: false,
              FulldayHotel:false,
              FulldayActivity:false,
              FulldayFlight:false,
              FulldayTransfer:false,
              FulldayHoteldescription:"Morning hotel description",
              FulldayTransferdescription:"Morning transfer description",
              FulldayFlightdescription:"Morning flight description",
              FulldayActivitydescription:"Morning activity description",
            },
            
            
          ],
          visa:{
            tittle: "Visa on arrival for Thailand",
            included: true,  // Add this field to determine if the insurance is excluded
            description: "The Visa fees includes single entry Thailand Visa and allied support from our team to obtain the Visa.",
            image: Insurance,  // Replace with the correct image path
          },
          Insurance:{
            title: "Travel Insurance for Thailand",
            plan: "50K Silver Plan for 2 People",
            description: "This is the average cost. Depending on the actual age of the travelers, the final cost will vary. We will update you when it does, be rest assured.",
            priceInfo: "Insurance prices are purely based on the age band you fall under. Prices might change once you input your age details in the next screen.",
            excluded: true,  // Add this field to determine if the insurance is excluded
            image: Insurance,  // Replace with the correct image path
          },
          flights:[Flight1, Flight2],
          Activities:[
            {
              Activityid:'1',
              ActivityheaderImages: [Australia1, Australia1, Australia1, Australia1,Australia1,Australia1,Australia1,Australia1,],
              ActivityOverview: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
              Activityimage: Insurance,
              ActivityName:"Activity1", 
              Date:"12/04/2024", 
              Starttime: "10:00 AM",
              time:"7 hrs", 
              activitytype:'private', 
              Activityamount:'Refundable', 
              Activityinclusions:["Elevator1","Bathtub1","Elevator1","Bathtub1"], 
              Activityexclusions:["Elevator","Bathtub"],
            },
              {
                Activityid:'2',
                ActivityheaderImages: [Australia1, Australia1, Australia1, Australia1,Australia1,Australia1,Australia1,Australia1,],
                ActivityOverview: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                Activityimage: Insurance,
                ActivityName:"Activity2", 
                Date:"12/04/2024",
                Starttime: "11:00 AM", 
                time:"7 hrs", 
                activitytype:'private', 
                Activityamount:'Refundable', 
                Activityinclusions:["Elevator","Bathtub"], 
                Activityexclusions:["Elevator","Bathtub"],
              },
          ],
          Transfer:[
            {
              Transferid:'1',
              Transferimage: Insurance,
              Transferfromto:"Pataya Yotel - Pucket Yotel", 
              TransferDate:"12/04/2024", 
              Transfernoofpeople:"2 No.s", 
              Transfertype:'Private', 
              Transfername:'Sedan', 
              Transferinformation:["Pickup from Pattaya Yotel","Drop at Yotel  Pucket",], 
            },
              {
                Transferid:'2',
              Transferimage: Insurance,
              Transferfromto:"Pataya Yotel - Pucket Yotel", 
              TransferDate:"12/04/2024", 
              Transfernoofpeople:"2 No.s", 
              Transfertype:'Public', 
              Transfername:'Sedan', 
              Transferinformation:["Pickup from Pattaya Yotel","Drop at Yotel  Pucket",],  
              },
          ],
          Hotels:[
            {
              Hotelid:'Hotel1',
              HotelOverview: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
              HotelheaderImages: [Australia1, Australia1, Australia1, Australia1,Australia1,Australia1,Australia1,Australia1,],
              Hotelimage: Insurance,
              WTRecommended: true,  // Add this field to determine if the insurance is excluded
              Hotelrating: 4.5,
              Hotelamount:'Refundable', 
              HotelDate:"12/04/2024", 
              Hotelarea:"Area 538 sqft", 
              Hoteltype:'5 Star',
              Hotelcheckintime:'14:00',
              Hotelcheckouttime:'14:00', 
              Hotelname:'Pucket Yotel1',
              Hotelaccomodates:'Accommodates 3 Adults', 
              Hotelinclusions:["Wifi","Room with Breakfast",'Air Conditioner'],
              Hotelexclusions:["Elevator","Bathtub"],
              HotelNearbyAttractions:[
                "Silom Complex Shopping Mall - 0.7 km / 0.5 mi",
                "Lumphini Park - 0.8 km / 0.5 mi",
                'Thaniya Plaza - 1.1 km / 0.7 mi',
                "Chulalongkorn Hospital - 1.2 km / 0.7 mi",
                "Chulalongkorn University - 1.4 km / 0.9 mi",
                'King Power MahaNakhon - 1.4 km / 0.9 mi',
                "Wat Hua Lamphong - 1.7 km / 1.1 mi",
                "Embassy of the United States - 1.9 km / 1.2 mi",
                'Samyan Mitrtown - 1.9 km / 1.2 mi',
                "Stock Exchange of Thailand - 2.7 km / 1.6 mi",
                "Siam Square - 2.7 km / 1.7 mi",
                'Erawan Shrine - 2.8 km / 1.7 mi',
              ],
              HotelAmenties:[
                "Elevator facility",
                "Concierge Service",
                'Laundry facility',
                "Common storage facility",
                "Pool accessories",
                'Locker Facility',
                "Gym/Fitness Centre",
                "Parking Facility",
                'Shuttle Service',
                "Spa facility",
                "Childcare Supervision",
              ],
              HotelInfo:'Hotels may charge a caution deposit on your credit card. It will be refunded within 10-15 days if there is no property damage.',
              Hoteladdress:'21/100 South Sathon Road,Bangkok,Bangkok,10120,TH ',
            },
            {
              Hotelid:'Hotel2',
              HotelOverview: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
              HotelheaderImages: [Insurance, Insurance, Insurance, Insurance, Insurance, Insurance, Insurance, Insurance,],
              Hotelimage: Insurance,
              WTRecommended: false,  // Add this field to determine if the insurance is excluded
              Hotelrating: 4.5,
              Hotelamount:'Refundable', 
              HotelDate:"12/04/2024", 
              Hotelarea:"Area 538 sqft", 
              Hoteltype:'5 Star', 
              Hotelname:'Pucket Yotel',
              Hotelaccomodates:'Accommodates 3 Adults', 
              Hotelinclusions:["Wifi","Room with Breakfast",'Air Conditioner'],
              Hotelexclusions:["Elevator","Bathtub"], 
              HotelInfo:'Hotels may charge a caution deposit on your credit card. It will be refunded within 10-15 days if there is no property damage.',
              Hoteladdress:'21/100 South Sathon Road,Bangkok,Bangkok,10120,TH ',
            },
          ],
        },
        {
          id: 2,
          Flighticon: <MdFlight className='flighticon' />,
          Activityicon: <TbTrekking className='Activityicon' />,
          Transfericon: <FaCarSide className='Transfericon' />,
          Hotelicon: <RiHotelFill className='Hotelicon' />,
          title: "7N/5 Days Bangkok Krabi Package",
          rating: 4,
          originalprice: 36000,
          offerprice: 32000,
          offerpercentage: 8,
          days: 5,
          EMI: "3472",
          loyality:"611",
          info: "dkhashgdvgsdvgasv",
          Inclusions:["wifi","Room with breakfast", "Air Conditioner"],
          Exclusions:["Elevator","Bathtub"],
          amenties:["5 Star","9 Activities", "Shared Transfer" , "24/7 Concierge"],
          image: Pattaya,
          information:'Filler text is text that shares some characteristics of a real written text, but is random or otherwise generated. It may be used to display a sample of fonts, generate text for testing, or to spoof an e-mail spam filter.',
        },
        {
          id: 3,
          Flighticon: <MdFlight className='flighticon' />,
          Activityicon: <TbTrekking className='Activityicon' />,
          Transfericon: <FaCarSide className='Transfericon' />,
          Hotelicon: <RiHotelFill className='Hotelicon' />,
          title: "8N/8 Days Dazzling Phuket Pattaya Package",
          rating: 3,
          originalprice: 45000,
          offerprice: 40000,
          offerpercentage: 8,
          days: 8,
          EMI: "3472",
          loyality:"611",
          info: "dkhashgdvgsdvgasv",
          Inclusions:["wifi","Room with breakfast", "Air Conditioner"],
          Exclusions:["Elevator","Bathtub"],
          amenties:["5 Star","9 Activities", "Shared Transfer" , "24/7 Concierge"],
          image: Pattaya, // Use the actual image link
          information:'Filler text is text that shares some characteristics of a real written text, but is random or otherwise generated. It may be used to display a sample of fonts, generate text for testing, or to spoof an e-mail spam filter.',
        },
        {
          id: 4,
          Flighticon: <MdFlight className='flighticon' />,
          Activityicon: <TbTrekking className='Activityicon' />,
          Transfericon: <FaCarSide className='Transfericon' />,
          Hotelicon: <RiHotelFill className='Hotelicon' />,
          title: "7N/12 Days Bangkok Krabi Package",
          rating: 2,
          originalprice: 46000,
          offerprice: 41000,
          offerpercentage: 8,
          days: 12,
          EMI: "3472",
          loyality:"611",
          info: "dkhashgdvgsdvgasv",
          Inclusions:["wifi","Room with breakfast", "Air Conditioner"],
          Exclusions:["Elevator","Bathtub"],
          amenties:["5 Star","9 Activities", "Shared Transfer" , "24/7 Concierge"],
          image: Pattaya,
          information:'Filler text is text that shares some characteristics of a real written text, but is random or otherwise generated. It may be used to display a sample of fonts, generate text for testing, or to spoof an e-mail spam filter.',
        },
        {
          id: 5,
          Flighticon: <MdFlight className='flighticon' />,
          Activityicon: <TbTrekking className='Activityicon' />,
          Transfericon: <FaCarSide className='Transfericon' />,
          Hotelicon: <RiHotelFill className='Hotelicon' />,
          title: "7N/12 Days Bangkok Krabi Package",
          rating: 5,
          originalprice: 56000,
          offerprice: 51000,
          offerpercentage: 8,
          days: 12,
          EMI: "3472",
          loyality:"611",
          info: "dkhashgdvgsdvgasv",
          Inclusions:["wifi","Room with breakfast", "Air Conditioner"],
          Exclusions:["Elevator","Bathtub"],
          amenties:["5 Star","9 Activities", "Shared Transfer" , "24/7 Concierge"],
          image: Pattaya,
          information:'Filler text is text that shares some characteristics of a real written text, but is random or otherwise generated. It may be used to display a sample of fonts, generate text for testing, or to spoof an e-mail spam filter.',
        },
        // Add more packages as per your requirement
      ]);
    const handleFilterChange = (filterValues) => {
        setFilters(filterValues);
      };
    return(
        <div className="packagefilter">
            {!isMobile && (<Filter  onFilterChange={handleFilterChange} />)}
            <PackageListing  packages={packages} filters={filters} />
        </div>
    );
};